<?php use Phalcon\Tag as Tag ?>

<?php echo $this->getContent() ?>

<div class="container">
    <div class="well">
        <h2>Login</h2>
        <?php echo Tag::form(array('users/login', 'class' => 'form-horizontal', 'autocomplete' => 'off')) ?>

            <div class="control-group">
                <label class="control-label">Email</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-envelope"></i></span>
                        <?php echo Tag::emailField(array('email', 'class' => 'input-xlarge', 'placeholder' => 'Email')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Password</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <?php echo Tag::passwordField(array('password', 'class' => 'input-xlarge', 'placeholder' => 'Password')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <?php echo Tag::submitButton(array('Login', 'class' => 'btn btn-primary')) ?> or
                    <?php echo Tag::linkTo(array("users/new", "Member Registration")) ?>
                </div>
            </div>
        </form>
    </div>
</div>