<?php use Phalcon\Tag as Tag ?>

<?php echo $this->getContent() ?>

<div class="center scaffold">

    <h2>Log In</h2>
    <hr>

    <?php echo Tag::form(array('users/login', 'class' => 'form-inline', 'autocomplete' => 'off')) ?>

    <div class="clearfix">
        <label for="username">Username:</label>
        <?php echo Tag::textField(array('username', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="clearfix">
        <label for="password">Password:</label>
        <?php echo Tag::passwordField(array('password', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="clearfix">
        <?php echo Tag::submitButton(array('Login', 'class' => 'btn btn-primary btn-medium')) ?> or
        <?php echo Tag::linkTo(array("users/new", "Member Registration")) ?>
    </div>
    <?php echo Tag::linkTo(array("users", "Lost password ?")) ?>
    </form>
</div>