<?php use Phalcon\Tag as Tag ?>


<?php echo $this->getContent() ?>

<div class="container">
    <div class="well">
            <?php echo Tag::form(array('users/register', 'class' => 'form-horizontal', 'autocomplete' => 'off')) ?>
            <legend>Sign Up</legend>
            <div class="control-group">
                <label class="control-label">First Name</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <?php echo Tag::textField(array('first_name', 'class' => 'input-xlarge', 'placeholder' => 'First Name')) ?>
                    </div>
                </div>
            </div>
            <div class="control-group ">
                <label class="control-label">Last Name</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <?php echo Tag::textField(array('last_name', 'class' => 'input-xlarge', 'placeholder' => 'Last Name')) ?>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Email</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-envelope"></i></span>
                        <?php echo Tag::emailField(array('email', 'class' => 'input-xlarge', 'placeholder' => 'Email')) ?>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Gender</label>
                <div class="controls">

                    <p><div id="gender" name="gender" class="btn-group" data-toggle="buttons-radio">
                        <button type="button" class="btn btn-info">Male</button>
                        <button type="button" class="btn btn-info">Female</button>

                    </div></p>

                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Password</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <?php echo Tag::passwordField(array('password', 'class' => 'input-xlarge', 'placeholder' => 'Password')) ?>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Confirm Password</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <?php echo Tag::passwordField(array('confirm_password', 'class' => 'input-xlarge', 'placeholder' => 'Re-enter Password')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Profile</label>
                <div class="controls">
                    <div class="input-prepend">
                        <?php echo Tag::textArea(array('profile', 'class' => 'ckeditor', 'placeholder' => 'Profile')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <?php echo Tag::submitButton(array('Create My Account', 'class' => 'btn btn-success')) ?>
                </div>

            </div>

        </form>

    </div>
</div>