<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form(array('users/register', 'class' => 'form-inline', 'autocomplete' => 'off')) ?>

<?php echo $this->getContent() ?>

<div class="center scaffold">

    <h2>Register</h2>
    <hr>

    <div class="form-group">
        <label for="username">Username:</label>
        <?php echo Tag::textField(array('username', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="form-group">
        <label for="email">Email:</label>
        <?php echo Tag::emailField(array('email', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="form-group">
        <label for="password">Password:</label>
        <?php echo Tag::passwordField(array('password', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="form-group">
        <label for="fullname">Full Name:</label>
        <?php echo Tag::textField(array('fullname', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="form-group">
        <label for="profile">Profile:</label>
        <?php echo Tag::textArea(array('profile', 'size' => "30")) ?>
    </div>
    <br/>
    <div class="form-group">
        <?php echo Tag::submitButton(array('Register', 'class' => 'btn btn-primary btn-medium')) ?>
    </div>
</div>
</form>
