<?php use Phalcon\Tag as Tag; ?>

<?php echo $this->getContent() ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("posts/new", "Create Posts", "class" => "btn btn-primary")) ?>
</div>
<p>
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Category</th>
        <th>description</th>
        <th>Action</th>
    </tr>
    <?php foreach($posts as $post){ ?>
        <tr>
            <td><?php echo $post->title ?></td>
            <td><?php echo $post->categories->name ?></td>
            <td><?php echo $post->description ?></td>
            <td><?php echo Tag::linkTo(array('posts/show/'.$post->id, 'Details', "class" => "btn btn-info")) ?>
                <?php echo \Phalcon\Tag::linkTo(array("posts/edit/".$post->id, "Edit", "class" => "btn btn-warning")) ?>
                <?php echo \Phalcon\Tag::linkTo(array("posts/delete/".$post->id, "Delete", "class" => "btn btn-danger")) ?>
            </td>
        </tr>
    <?php } ?>
</table>
</p>