<?php use Phalcon\Tag as Tag; ?>

<?php echo $this->getContent() ?>
<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("posts/new", "Create Posts", "class" => "btn")) ?>
</div>
<p>
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Created</th>
        <th>Slug</th>
    </tr>
    <?php foreach($posts as $post){ ?>
        <tr>
            <td><?php echo $post->title ?></td>
            <td><?php echo $post->created ?></td>
            <td><?php echo Tag::linkTo('posts/show/'.$post->slug, 'Details') ?></td>
        </tr>
    <?php } ?>
</table>
</p>