<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form(array("posts/create", "autocomplete" => "off")) ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("posts", "&larr; Go Back", "class" => "btn")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="center scaffold">
    <h2>Create posts</h2>
    <hr>
    <div class="clearfix">
        <label for="categories_id">Categories</label>
        <?php echo Tag::select(array("categories_id", $categories, "using" => array("id", "name"), "useDummy" => true)) ?>
    </div>

    <div class="clearfix">
        <label for="title">Title</label>
        <?php echo Tag::textField(array("title", "size" => 40, "maxlength" => 100)) ?>
    </div>

    <div class="clearfix">
        <label for="description">description</label>
        <?php echo Tag::textField(array("description", "size" => 24, "maxlength" => 70)) ?>
    </div>

    <div class="clearfix">
        <label for="content">Content</label>
        <?php echo Tag::textArea(array("content", "size" => 40, "class"=> "ckeditor")) ?>

    </div>
    <div class="clearfix">
        <?php echo Tag::submitButton(array("Save", "class" => "btn btn-success")) ?>
    </div>
</div>
</form>