<?php use Phalcon\Tag as Tag ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("posts", "&larr; Go Back")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="container">
    <div class="well">
        <?php echo Tag::form(array("posts/create", 'class' => 'form-horizontal', "autocomplete" => "off")) ?>
            <legend>Create Post</legend>
            <div class="control-group">
                <label class="control-label">Category</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-pencil"></i></span>
                        <?php echo Tag::select(array("categories_id", $categories, "using" => array("id", "name"), "useDummy" => true)) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Title</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-pencil"></i></span>
                        <?php echo Tag::textField(array('title','class' => 'input-xlarge', 'placeholder' => 'Title')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Description</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-pencil"></i></span>
                        <?php echo Tag::textField(array('description','class' => 'input-xlarge', 'placeholder' => 'Description')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Content</label>
                <div class="controls">
                    <div class="input-prepend">
                        <?php echo Tag::textArea(array('content','class' => 'ckeditor')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <?php echo Tag::submitButton(array('Create Post', 'class' => 'btn btn-success')) ?>
                </div>
            </div>
        </form>
    </div>
</div>
