<?php use Phalcon\Tag as Tag; ?>
<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo('posts/index', '← Go back ') ?>
    </li>
</ul>
<div class="container">

    <h1>
        <?php echo $post->title ?>
    </h1>
    <small>
        <em>created <?php echo $post->created ?> by <?php echo $post->getUsers()->email ?> | Category: <?php echo $post->categories->name ?></em>
    </small>
    <br/>
    <p>
        <?php echo $post->content ?>
    </p>
    <br/>
</div>