<?php use Phalcon\Tag as Tag ?>

<?php echo Tag::form(array("categories/save", "autocomplete" => "off")) ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("categories", "&larr; Go Back", "class" => "btn")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="center scaffold">
    <h2>Edit Category</h2>
    <hr>
    <div class="clearfix">
        <label for="title">Name</label>
        <?php echo Tag::textField(array("name", "size" => 40, "maxlength" => 100)) ?>
    </div>

    <div class="clearfix">
        <label for="description">Description</label>
        <?php echo Tag::textField(array("description", "size" => 24, "maxlength" => 70)) ?>
    </div>

    <div class="clearfix">
        <?php echo $this->tag->hiddenField("id") ?>
        <?php echo Tag::submitButton(array("Save", "class" => "btn btn-success")) ?>
    </div>

</div>
</form>