<?php use Phalcon\Tag as Tag ?>

<ul class="pager">
    <li class="previous pull-left">
        <?php echo Tag::linkTo(array("categories", "&larr; Go Back")) ?>
    </li>
</ul>

<?php echo $this->getContent() ?>

<div class="container">
    <div class="well">
        <?php echo Tag::form(array('categories/save', 'class' => 'form-horizontal', 'autocomplete' => 'off')) ?>
            <legend>Edit Category</legend>
            <div class="control-group">
                <label class="control-label">Name</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-pencil"></i></span>
                        <?php echo Tag::textField(array('name','class' => 'input-xlarge', 'placeholder' => 'Name')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Description</label>
                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-pencil"></i></span>
                        <?php echo Tag::textField(array('description','class' => 'input-xlarge', 'placeholder' => 'Description')) ?>
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <?php echo $this->tag->hiddenField("id") ?>
                    <?php echo Tag::submitButton(array('Edit Category', 'class' => 'btn btn-success')) ?>
                </div>
            </div>
        </form>
    </div>
</div>
