<?php use Phalcon\Tag as Tag; ?>
<?php echo $this->getContent(); ?>

<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("categories/new", "Create Categories", "class" => "btn btn-primary")) ?>
</div>
<br/>
<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Action</th>
    </tr>
    <?php foreach($categories as $category){ ?>
        <tr>
            <td><?php echo $category->name ?></td>
            <td><?php echo $category->description ?></td>
            <td><?php echo \Phalcon\Tag::linkTo(array("categories/edit/".$category->id, "Edit", "class" => "btn btn-warning")) ?> 
                <?php echo \Phalcon\Tag::linkTo(array("categories/delete/".$category->id, "Delete", "class" => "btn btn-danger")) ?>
            </td>
        </tr>
    <?php } ?>
    <tr>

    </tr>
</table>