<?php use Phalcon\Tag as Tag; ?>
<?php echo $this->getContent(); ?>

<div align="right">
    <?php echo \Phalcon\Tag::linkTo(array("categories/new", "Create Categories", "class" => "btn")) ?>
</div>

<table class="table table-striped">
    <tr>
        <th>Title</th>
        <th>Slug</th>
    </tr>
    <?php foreach($categories as $category){ ?>
        <tr>
            <td><?php echo $category->name ?></td>
            <td><?php echo Tag::linkTo('categories/show/'.$post->slug, 'Details') ?></td>
        </tr>
    <?php } ?>
</table>